/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/radio.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, -0.586, 0.742]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.342}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Player_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Player_2.geometry}
          material={materials["Default OBJ"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Player_3.geometry}
          material={materials["Default OBJ"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Player_4.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Player_5.geometry}
          material={materials.initialShadingGroup}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Player_6.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Player_7.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Player_8.geometry}
          material={materials.aiStandardSurface14SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Player_9.geometry}
          material={materials["Default OBJ"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/radio.glb");
